--------------------------------------------------------
-- Archivo creado  - viernes-mayo-16-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."USERS" 
   (	"USER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERNAME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."CATEGORIES" 
   (	"CATEGORY_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(255 BYTE), 
	"DESCRIPTION" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"TEAM_ID" NUMBER, 
	"ROLE" VARCHAR2(255 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MODULES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MODULES" 
   (	"MODULE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITLE" VARCHAR2(255 BYTE), 
	"BODY" CLOB, 
	"CATEGORY_ID" NUMBER, 
	"STATUS" NUMBER(1,0), 
	"SEVERITY" NUMBER, 
	"START_DATE" DATE, 
	"DATE_LIMIT" DATE, 
	"PARENT_MODULE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BODY") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE( INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table MOVIE_SALES_FACT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MOVIE_SALES_FACT" 
   (	"ORDER_NUM" NUMBER, 
	"DAY" DATE, 
	"DAY_NUM_OF_WEEK" NUMBER, 
	"DAY_NAME" VARCHAR2(4000 BYTE), 
	"MONTH" VARCHAR2(4000 BYTE), 
	"MONTH_NUM_OF_YEAR" NUMBER, 
	"MONTH_NAME" VARCHAR2(4000 BYTE), 
	"QUARTER_NAME" VARCHAR2(4000 BYTE), 
	"QUARTER_NUM_OF_YEAR" NUMBER, 
	"YEAR" NUMBER, 
	"CUSTOMER_ID" NUMBER, 
	"USERNAME" VARCHAR2(4000 BYTE), 
	"CUSTOMER_NAME" VARCHAR2(4000 BYTE), 
	"STREET_ADDRESS" VARCHAR2(4000 BYTE), 
	"POSTAL_CODE" VARCHAR2(4000 BYTE), 
	"CITY_ID" NUMBER, 
	"CITY" VARCHAR2(4000 BYTE), 
	"STATE_PROVINCE_ID" NUMBER, 
	"STATE_PROVINCE" VARCHAR2(4000 BYTE), 
	"COUNTRY_ID" NUMBER, 
	"COUNTRY" VARCHAR2(4000 BYTE), 
	"COUNTRY_CODE" VARCHAR2(4000 BYTE), 
	"CONTINENT" VARCHAR2(4000 BYTE), 
	"SEGMENT_NAME" VARCHAR2(4000 BYTE), 
	"SEGMENT_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"CREDIT_BALANCE" NUMBER, 
	"EDUCATION" VARCHAR2(4000 BYTE), 
	"EMAIL" VARCHAR2(4000 BYTE), 
	"FULL_TIME" VARCHAR2(4000 BYTE), 
	"GENDER" VARCHAR2(4000 BYTE), 
	"HOUSEHOLD_SIZE" NUMBER, 
	"HOUSEHOLD_SIZE_BAND" VARCHAR2(4000 BYTE), 
	"WORK_EXPERIENCE" NUMBER, 
	"WORK_EXPERIENCE_BAND" VARCHAR2(4000 BYTE), 
	"INSUFF_FUNDS_INCIDENTS" NUMBER, 
	"JOB_TYPE" VARCHAR2(4000 BYTE), 
	"LATE_MORT_RENT_PMTS" NUMBER, 
	"MARITAL_STATUS" VARCHAR2(4000 BYTE), 
	"MORTGAGE_AMT" NUMBER, 
	"NUM_CARS" NUMBER, 
	"NUM_MORTGAGES" NUMBER, 
	"PET" VARCHAR2(4000 BYTE), 
	"PROMOTION_RESPONSE" NUMBER, 
	"RENT_OWN" VARCHAR2(4000 BYTE), 
	"YEARS_CURRENT_EMPLOYER" NUMBER, 
	"YEARS_CURRENT_EMPLOYER_BAND" VARCHAR2(4000 BYTE), 
	"YEARS_CUSTOMER" NUMBER, 
	"YEARS_CUSTOMER_BAND" VARCHAR2(4000 BYTE), 
	"YEARS_RESIDENCE" NUMBER, 
	"YEARS_RESIDENCE_BAND" VARCHAR2(4000 BYTE), 
	"AGE" NUMBER, 
	"AGE_BAND" VARCHAR2(4000 BYTE), 
	"COMMUTE_DISTANCE" NUMBER, 
	"COMMUTE_DISTANCE_BAND" VARCHAR2(4000 BYTE), 
	"INCOME" NUMBER, 
	"INCOME_BAND" VARCHAR2(4000 BYTE), 
	"MOVIE_ID" NUMBER, 
	"SEARCH_GENRE" VARCHAR2(4000 BYTE), 
	"TITLE" VARCHAR2(4000 BYTE), 
	"GENRE" VARCHAR2(4000 BYTE), 
	"SKU" NUMBER, 
	"LIST_PRICE" NUMBER, 
	"APP" VARCHAR2(4000 BYTE), 
	"DEVICE" VARCHAR2(4000 BYTE), 
	"OS" VARCHAR2(4000 BYTE), 
	"PAYMENT_METHOD" VARCHAR2(4000 BYTE), 
	"DISCOUNT_TYPE" VARCHAR2(4000 BYTE), 
	"DISCOUNT_PERCENT" NUMBER, 
	"ACTUAL_PRICE" NUMBER, 
	"QUANTITY_SOLD" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."ORDER_NUM" IS '{"fieldName":"ORDER_NUM"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."DAY" IS '{"fieldName":"DAY"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."DAY_NUM_OF_WEEK" IS '{"fieldName":"DAY_NUM_OF_WEEK"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."DAY_NAME" IS '{"fieldName":"DAY_NAME"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."MONTH" IS '{"fieldName":"MONTH"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."MONTH_NUM_OF_YEAR" IS '{"fieldName":"MONTH_NUM_OF_YEAR"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."MONTH_NAME" IS '{"fieldName":"MONTH_NAME"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."QUARTER_NAME" IS '{"fieldName":"QUARTER_NAME"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."QUARTER_NUM_OF_YEAR" IS '{"fieldName":"QUARTER_NUM_OF_YEAR"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."YEAR" IS '{"fieldName":"YEAR"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."CUSTOMER_ID" IS '{"fieldName":"CUSTOMER_ID"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."USERNAME" IS '{"fieldName":"USERNAME"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."CUSTOMER_NAME" IS '{"fieldName":"CUSTOMER_NAME"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."STREET_ADDRESS" IS '{"fieldName":"STREET_ADDRESS"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."POSTAL_CODE" IS '{"fieldName":"POSTAL_CODE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."CITY_ID" IS '{"fieldName":"CITY_ID"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."CITY" IS '{"fieldName":"CITY"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."STATE_PROVINCE_ID" IS '{"fieldName":"STATE_PROVINCE_ID"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."STATE_PROVINCE" IS '{"fieldName":"STATE_PROVINCE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."COUNTRY_ID" IS '{"fieldName":"COUNTRY_ID"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."COUNTRY" IS '{"fieldName":"COUNTRY"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."COUNTRY_CODE" IS '{"fieldName":"COUNTRY_CODE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."CONTINENT" IS '{"fieldName":"CONTINENT"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."SEGMENT_NAME" IS '{"fieldName":"SEGMENT_NAME"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."SEGMENT_DESCRIPTION" IS '{"fieldName":"SEGMENT_DESCRIPTION"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."CREDIT_BALANCE" IS '{"fieldName":"CREDIT_BALANCE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."EDUCATION" IS '{"fieldName":"EDUCATION"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."EMAIL" IS '{"fieldName":"EMAIL"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."FULL_TIME" IS '{"fieldName":"FULL_TIME"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."GENDER" IS '{"fieldName":"GENDER"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."HOUSEHOLD_SIZE" IS '{"fieldName":"HOUSEHOLD_SIZE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."HOUSEHOLD_SIZE_BAND" IS '{"fieldName":"HOUSEHOLD_SIZE_BAND"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."WORK_EXPERIENCE" IS '{"fieldName":"WORK_EXPERIENCE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."WORK_EXPERIENCE_BAND" IS '{"fieldName":"WORK_EXPERIENCE_BAND"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."INSUFF_FUNDS_INCIDENTS" IS '{"fieldName":"INSUFF_FUNDS_INCIDENTS"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."JOB_TYPE" IS '{"fieldName":"JOB_TYPE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."LATE_MORT_RENT_PMTS" IS '{"fieldName":"LATE_MORT_RENT_PMTS"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."MARITAL_STATUS" IS '{"fieldName":"MARITAL_STATUS"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."MORTGAGE_AMT" IS '{"fieldName":"MORTGAGE_AMT"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."NUM_CARS" IS '{"fieldName":"NUM_CARS"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."NUM_MORTGAGES" IS '{"fieldName":"NUM_MORTGAGES"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."PET" IS '{"fieldName":"PET"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."PROMOTION_RESPONSE" IS '{"fieldName":"PROMOTION_RESPONSE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."RENT_OWN" IS '{"fieldName":"RENT_OWN"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."YEARS_CURRENT_EMPLOYER" IS '{"fieldName":"YEARS_CURRENT_EMPLOYER"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."YEARS_CURRENT_EMPLOYER_BAND" IS '{"fieldName":"YEARS_CURRENT_EMPLOYER_BAND"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."YEARS_CUSTOMER" IS '{"fieldName":"YEARS_CUSTOMER"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."YEARS_CUSTOMER_BAND" IS '{"fieldName":"YEARS_CUSTOMER_BAND"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."YEARS_RESIDENCE" IS '{"fieldName":"YEARS_RESIDENCE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."YEARS_RESIDENCE_BAND" IS '{"fieldName":"YEARS_RESIDENCE_BAND"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."AGE" IS '{"fieldName":"AGE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."AGE_BAND" IS '{"fieldName":"AGE_BAND"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."COMMUTE_DISTANCE" IS '{"fieldName":"COMMUTE_DISTANCE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."COMMUTE_DISTANCE_BAND" IS '{"fieldName":"COMMUTE_DISTANCE_BAND"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."INCOME" IS '{"fieldName":"INCOME"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."INCOME_BAND" IS '{"fieldName":"INCOME_BAND"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."MOVIE_ID" IS '{"fieldName":"MOVIE_ID"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."SEARCH_GENRE" IS '{"fieldName":"SEARCH_GENRE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."TITLE" IS '{"fieldName":"TITLE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."GENRE" IS '{"fieldName":"GENRE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."SKU" IS '{"fieldName":"SKU"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."LIST_PRICE" IS '{"fieldName":"LIST_PRICE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."APP" IS '{"fieldName":"APP"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."DEVICE" IS '{"fieldName":"DEVICE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."OS" IS '{"fieldName":"OS"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."PAYMENT_METHOD" IS '{"fieldName":"PAYMENT_METHOD"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."DISCOUNT_TYPE" IS '{"fieldName":"DISCOUNT_TYPE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."DISCOUNT_PERCENT" IS '{"fieldName":"DISCOUNT_PERCENT"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."ACTUAL_PRICE" IS '{"fieldName":"ACTUAL_PRICE"}';
   COMMENT ON COLUMN "ADMIN"."MOVIE_SALES_FACT"."QUANTITY_SOLD" IS '{"fieldName":"QUANTITY_SOLD"}';
--------------------------------------------------------
--  DDL for Table OSDDMW_DIAGRAMS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."OSDDMW_DIAGRAMS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(70 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"GLOBAL_ID" VARCHAR2(70 BYTE), 
	"DESIGN_ID" VARCHAR2(70 BYTE), 
	"DESIGN_NAME" VARCHAR2(256 BYTE), 
	"MODEL_ID" VARCHAR2(70 BYTE), 
	"MODEL_NAME" VARCHAR2(256 BYTE), 
	"SUBVIEW_ID" VARCHAR2(70 BYTE), 
	"SUBVIEW_NAME" VARCHAR2(256 BYTE), 
	"PARENT_ID" VARCHAR2(70 BYTE), 
	"DIAGRAM_TYPE" VARCHAR2(10 BYTE), 
	"LAYOUT" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("LAYOUT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TASKS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TASKS" 
   (	"TASK_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITLE" VARCHAR2(255 BYTE), 
	"MODULE_ID" NUMBER, 
	"DESCRIPTION" CLOB, 
	"DATE_LIMIT" DATE, 
	"RESPONSIBLE" NUMBER, 
	"ENDING_DATE" DATE, 
	"ESTIMATED_TIME" NUMBER, 
	"ACTUAL_TIME" NUMBER, 
	"CREATION_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"DONE" NUMBER(10,0) DEFAULT 0, 
	"STORY_POINTS" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE( INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TEAMS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TEAMS" 
   (	"TEAM_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TEAM_NAME" VARCHAR2(255 BYTE), 
	"TEAM_SIZE" NUMBER, 
	"MANAGER" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEAMS_WORKING_MODULES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TEAMS_WORKING_MODULES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MODULE_ID" NUMBER, 
	"TEAM_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TODOITEM
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TODOITEM" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"CREATION_TS" TIMESTAMP (6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	"DONE" NUMBER(1,0), 
	"STORY_POINTS" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.USERS
SET DEFINE OFF;
REM INSERTING into ADMIN.CATEGORIES
SET DEFINE OFF;
REM INSERTING into ADMIN.EMPLOYEES
SET DEFINE OFF;
REM INSERTING into ADMIN.MODULES
SET DEFINE OFF;
REM INSERTING into ADMIN.MOVIE_SALES_FACT
SET DEFINE OFF;
REM INSERTING into ADMIN.OSDDMW_DIAGRAMS
SET DEFINE OFF;
Insert into ADMIN.OSDDMW_DIAGRAMS (ID,NAME,DESCRIPTION,LAST_UPDATE,GLOBAL_ID,DESIGN_ID,DESIGN_NAME,MODEL_ID,MODEL_NAME,SUBVIEW_ID,SUBVIEW_NAME,PARENT_ID,DIAGRAM_TYPE) values (1,'DataBase initial model','Data Modeler Web Diagram',to_timestamp('27/02/25 17:19:12.898359000','DD/MM/RR HH24:MI:SSXFF'),'37A3BE3C-7D32-0303-C871-2E13D2983F29',null,null,null,null,null,null,null,null);
REM INSERTING into ADMIN.TASKS
SET DEFINE OFF;
REM INSERTING into ADMIN.TEAMS
SET DEFINE OFF;
REM INSERTING into ADMIN.TEAMS_WORKING_MODULES
SET DEFINE OFF;
REM INSERTING into ADMIN.TODOITEM
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C0040239
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0040239" ON "ADMIN"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0040229
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0040229" ON "ADMIN"."CATEGORIES" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0040233
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0040233" ON "ADMIN"."EMPLOYEES" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0040227
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0040227" ON "ADMIN"."MODULES" ("MODULE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OSDDMW_DIAGRAMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."OSDDMW_DIAGRAMS_PK" ON "ADMIN"."OSDDMW_DIAGRAMS" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OSDDMW_DIAGRAMS_UK_GUID
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."OSDDMW_DIAGRAMS_UK_GUID" ON "ADMIN"."OSDDMW_DIAGRAMS" ("GLOBAL_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OSDDMW_DIAGRAMS_DESDIX
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."OSDDMW_DIAGRAMS_DESDIX" ON "ADMIN"."OSDDMW_DIAGRAMS" ("DESIGN_ID", "MODEL_ID", "SUBVIEW_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0040225
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0040225" ON "ADMIN"."TASKS" ("TASK_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0040235
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0040235" ON "ADMIN"."TEAMS" ("TEAM_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0040223
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0040223" ON "ADMIN"."TEAMS_WORKING_MODULES" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0040286
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0040286" ON "ADMIN"."TODOITEM" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."CATEGORIES" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CATEGORIES" ADD PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EMPLOYEES" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EMPLOYEES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EMPLOYEES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EMPLOYEES" ADD PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MODULES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MODULES" MODIFY ("MODULE_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MODULES" ADD PRIMARY KEY ("MODULE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OSDDMW_DIAGRAMS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."OSDDMW_DIAGRAMS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."OSDDMW_DIAGRAMS" ADD CONSTRAINT "OSDDMW_DIAGRAMS_PK" PRIMARY KEY ("ID")
  USING INDEX "ADMIN"."OSDDMW_DIAGRAMS_PK"  ENABLE;
  ALTER TABLE "ADMIN"."OSDDMW_DIAGRAMS" ADD CONSTRAINT "OSDDMW_DIAGRAMS_UK_GUID" UNIQUE ("GLOBAL_ID")
  USING INDEX "ADMIN"."OSDDMW_DIAGRAMS_UK_GUID"  ENABLE;
  ALTER TABLE "ADMIN"."OSDDMW_DIAGRAMS" ADD CONSTRAINT "OSDDMW_DIAGRAMS_DESDIX" UNIQUE ("DESIGN_ID", "MODEL_ID", "SUBVIEW_ID")
  USING INDEX "ADMIN"."OSDDMW_DIAGRAMS_DESDIX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TASKS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TASKS" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TASKS" ADD PRIMARY KEY ("TASK_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEAMS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TEAMS" MODIFY ("TEAM_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TEAMS" ADD PRIMARY KEY ("TEAM_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEAMS_WORKING_MODULES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TEAMS_WORKING_MODULES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TEAMS_WORKING_MODULES" MODIFY ("MODULE_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TEAMS_WORKING_MODULES" MODIFY ("TEAM_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TEAMS_WORKING_MODULES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TODOITEM
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TODOITEM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TODOITEM" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EMPLOYEES" ADD CONSTRAINT "FK_EMPLOYEES_USERS" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ADMIN"."EMPLOYEES" ADD CONSTRAINT "FK_EMPLOYEES_TEAMS" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "ADMIN"."TEAMS" ("TEAM_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MODULES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MODULES" ADD CONSTRAINT "FK_MODULES_CATEGORIES" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "ADMIN"."CATEGORIES" ("CATEGORY_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ADMIN"."MODULES" ADD CONSTRAINT "FK_MODULES_SELF" FOREIGN KEY ("PARENT_MODULE")
	  REFERENCES "ADMIN"."MODULES" ("MODULE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TASKS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TASKS" ADD CONSTRAINT "FK_TASKS_MODULES" FOREIGN KEY ("MODULE_ID")
	  REFERENCES "ADMIN"."MODULES" ("MODULE_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ADMIN"."TASKS" ADD CONSTRAINT "FK_TASKS_EMPLOYEES" FOREIGN KEY ("RESPONSIBLE")
	  REFERENCES "ADMIN"."EMPLOYEES" ("EMPLOYEE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEAMS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TEAMS" ADD CONSTRAINT "FK_TEAMS_MANAGER" FOREIGN KEY ("MANAGER")
	  REFERENCES "ADMIN"."EMPLOYEES" ("EMPLOYEE_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEAMS_WORKING_MODULES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TEAMS_WORKING_MODULES" ADD CONSTRAINT "FK_TWM_MODULES" FOREIGN KEY ("MODULE_ID")
	  REFERENCES "ADMIN"."MODULES" ("MODULE_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ADMIN"."TEAMS_WORKING_MODULES" ADD CONSTRAINT "FK_TWM_TEAMS" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "ADMIN"."TEAMS" ("TEAM_ID") ON DELETE CASCADE ENABLE;
